=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/ARCHIVOS_FINALES/BibliotecaDTD/bDTD.dtd
<!ELEMENT biblioteca (libros,revistas,periodicos)>
<!ATTLIST biblioteca nombre CDATA #REQUIRED>
<!-- #REQUIRED: El atributo es obligatorio.  
      CDATA: Datos de caracteres no analizados sintácticamente. -->


    <!ELEMENT libros (libro+)>
    <!-- Con el signo más (+) definimos que debe de aparecer por lo menos una vez. -->
    <!ELEMENT libro (titulo_libro,autor_libro,indice_libro,sinopsis)>
      <!ATTLIST libro id ID #REQUIRED> <!-- En id se pone que es de tipo ID para que se identifique como valor unico y no se pueda repetir-->
      <!ATTLIST libro tipo_clase CDATA #REQUIRED>
      <!ATTLIST libro num_pag CDATA #REQUIRED>
      <!ELEMENT titulo_libro (#PCDATA)>
      <!-- Datos de carácter. Cuando un elemento solo va a contener datos de carácter analizados sintácticamente, se utiliza la
declaración (#PCDATA) -->
      <!ELEMENT autor_libro (#PCDATA)>
      <!ELEMENT indice_libro (capitulo+)>
      <!ELEMENT capitulo (titulo_capitulo,contenido_libro)>
        <!ATTLIST capitulo num CDATA #REQUIRED>
        <!ATTLIST capitulo num_pag CDATA #REQUIRED>
        <!ELEMENT titulo_capitulo (#PCDATA)>
        <!ELEMENT contenido_libro (#PCDATA)>
        <!ATTLIST contenido_libro enlace_info CDATA #REQUIRED>
      <!ELEMENT sinopsis (#PCDATA)>

    <!ELEMENT revistas (revista+)>
      <!ELEMENT revista (titulo_revista,num_revista,indice_revista)>
        <!ATTLIST revista id ID #REQUIRED>
        <!ATTLIST revista tipo_clase CDATA #REQUIRED>
        <!ATTLIST revista num_pag CDATA #REQUIRED>
        <!ELEMENT titulo_revista (#PCDATA)>
        <!ELEMENT num_revista (#PCDATA)>
        <!ELEMENT indice_revista (seccion_revista+)>
          <!ELEMENT seccion_revista (contenido_revista)>
          <!ATTLIST seccion_revista num CDATA #REQUIRED>
          <!ATTLIST seccion_revista num_pag CDATA #REQUIRED>
          <!ELEMENT contenido_revista (#PCDATA)>
          <!ATTLIST contenido_revista enlace_info CDATA #REQUIRED>
    
    <!ELEMENT periodicos (periodico+)>
      <!ELEMENT periodico (titulo,indice)>
      <!ATTLIST periodico id ID #REQUIRED >
      <!ATTLIST periodico tipo_clase CDATA #REQUIRED >
      <!ATTLIST periodico num_pag CDATA #REQUIRED >
      <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
      <!ELEMENT titulo (#PCDATA)>
      <!ELEMENT indice (seccion+)>
        <!ELEMENT seccion (articulo+)>
          <!ATTLIST seccion num CDATA #REQUIRED>
          <!ATTLIST seccion num_pag CDATA #REQUIRED>
          <!ATTLIST seccion tipo_seccion CDATA #REQUIRED>
          <!ELEMENT articulo (autor,contenido)>
          <!ATTLIST articulo num CDATA #REQUIRED>
          <!ATTLIST articulo num_pag CDATA #REQUIRED>
          <!ELEMENT autor (#PCDATA)>
          <!ELEMENT contenido (#PCDATA)>
          <!ATTLIST contenido enlace_info CDATA #REQUIRED>

=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/ARCHIVOS_FINALES/BibliotecaDTD/bXML.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<!DOCTYPE biblioteca SYSTEM "bDTD.dtd">
<biblioteca  nombre= "eBiblio Madrid">
    <!--Estructuramos el catálogo en libros, revistas y periódicos-->
    <libros>

        <!--Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo identificativo de su clase denominado tipo_clase.-->
        <libro id="L0001" tipo_clase="Novela" num_pag="120">
            <titulo_libro>Aquitania</titulo_libro>
            <autor_libro>Eva García Sáenz de Urturi</autor_libro>
            <indice_libro>
                <capitulo num="1" num_pag="25" >
                    <titulo_capitulo>"La muerte azul"</titulo_capitulo>
                    <!--Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a la información.-->
                    <contenido_libro enlace_info="https://madrid.ebiblio.es/resources/5fcfb81d6af9f8028931014b"></contenido_libro>
                </capitulo>
                <capitulo num="2" num_pag="30" >
                    <titulo_capitulo>"La ciudad infinita"</titulo_capitulo>
                    <contenido_libro enlace_info="https://madrid.ebiblio.es/resources/5fcfb81d6af9f8028931014b"></contenido_libro>
                </capitulo>
            </indice_libro> 
            <sinopsis>
                Un cautivador thriller histórico que atraviesa un siglo repleto de venganzas y batallas. Un turbador misterio en torno atres vidas que forjarán lo que más tarde se llamará Europa.
            </sinopsis>
        </libro>

        <libro id="L0002" tipo_clase="Infantil" num_pag="100">
            <titulo_libro>¿De qué color es?</titulo_libro>
            <autor_libro>Gottlieb Suzanne</autor_libro>
            <indice_libro>
                <capitulo num="1" num_pag="3" >
                    <titulo_capitulo>"Colores en la naturaleza"</titulo_capitulo>
                    <contenido_libro enlace_info="https://madrid.ebiblio.es/resources/5fcfb0dc6af9f8028930683c"></contenido_libro>
                </capitulo>
                <capitulo num="2" num_pag="5" >
                    <titulo_capitulo>"Los azules"</titulo_capitulo>
                    <contenido_libro enlace_info="https://madrid.ebiblio.es/resources/5fcfb0dc6af9f8028930683c"></contenido_libro>
                </capitulo>
            </indice_libro> 
            <sinopsis>
                En ¿De qué color es? el pequeño Jonny descubre el significado de los colores mientras explora el paisaje que le rodea. Jonny moja los pies en un arroyo azul, recoge flores de color violeta, excava la tierra marrón y encuentra una gran calabaza de color naranja. Finalmente el sol amarillo y la noche negra le muestran cuál es el momento para despertarse y para ir a dormir.
            </sinopsis>
        </libro>

        <libro id="L0003" tipo_clase="Didáctico" num_pag="90">
            <titulo_libro>El último alquimista en París</titulo_libro>
            <autor_libro>Lars Öhrström</autor_libro>
            <indice_libro>
                <capitulo num="1" num_pag="30" >
                    <titulo_capitulo>"Mr Khama viene a cenar"</titulo_capitulo>
                    <contenido_libro enlace_info="https://madrid.ebiblio.es/resources/5fcfb1966af9f802893077e3"></contenido_libro>
                </capitulo>
                <capitulo num="2" num_pag="26" >
                    <titulo_capitulo>"Desde Bitterfeld con amor"</titulo_capitulo>
                    <contenido_libro enlace_info="https://madrid.ebiblio.es/resources/5fcfb1966af9f802893077e3"></contenido_libro>
                </capitulo>
            </indice_libro> 
            <sinopsis>
                Este es un libro sobre el descubrimiento y el desastre, la guerra y la ciencia - y la relación entre los seres humanos y los elementos químicos que componen nuestro planeta. Lars Öhrström nos acerca a una gran variedad de elementos, del azufre al plomo, a través de historias de personas ordinarias y extraordinarias de todo el mundo. 
            </sinopsis>
        </libro>
   
    </libros>

<!--Las revistas a su vez son clasificadas en: informática, corazón, coches, investigación y otras.-->

    <revistas>
        <revista id="R0001" tipo_clase="Informática" num_pag="60">
            <titulo_revista>"Computer Hoy"</titulo_revista>
            <num_revista>1452021</num_revista>
            <indice_revista>
                <seccion_revista num="1" num_pag="25" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/609dca4bc02842000180f102"></contenido_revista>
                </seccion_revista>
                <seccion_revista num="2" num_pag="12" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/609dca4bc02842000180f102"></contenido_revista>
                </seccion_revista>
            </indice_revista> 
        </revista>
        <revista id="R0002" tipo_clase="Corazón" num_pag="50">
            <titulo_revista>"Semana"</titulo_revista>
            <num_revista>1252021</num_revista>
            <indice_revista>
                <seccion_revista num="1" num_pag="15" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/609c08d650b8bd0001b5e34a"></contenido_revista>
                </seccion_revista>
                <seccion_revista num="2" num_pag="12" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/609c08d650b8bd0001b5e34a"></contenido_revista>
                </seccion_revista>
            </indice_revista> 
        </revista>
        <revista id="R0003" tipo_clase="Coches" num_pag="70">
            <titulo_revista>"Autofácil"</titulo_revista>
            <num_revista>152021</num_revista>
            <indice_revista>
                <seccion_revista num="1" num_pag="13" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/608cdf92488c920001f58b33"></contenido_revista>
                </seccion_revista>
                <seccion_revista num="2" num_pag="11" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/608cdf92488c920001f58b33"></contenido_revista>
                </seccion_revista>
            </indice_revista> 
        </revista>
        <revista id="R0004" tipo_clase="Investigación" num_pag="70">
            <titulo_revista>"National Geographic"</titulo_revista>
            <num_revista>2142021</num_revista>
            <indice_revista>
                <seccion_revista num="1" num_pag="13" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/607f786dff0e7e00016af832"></contenido_revista>
                </seccion_revista>
                <seccion_revista num="2" num_pag="11" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/607f786dff0e7e00016af832"></contenido_revista>
                </seccion_revista>
            </indice_revista> 
        </revista>
        <revista id="R0005" tipo_clase="Otras" num_pag="45">
            <titulo_revista>"Fotogramas"</titulo_revista>
            <num_revista>2942021</num_revista>
            <indice_revista>
                <seccion_revista num="1" num_pag="13" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/608a111029fb970001adb3e6"></contenido_revista>
                </seccion_revista>
                <seccion_revista num="2" num_pag="11" >
                    <contenido_revista enlace_info="https://madrid.ebiblio.es/resources/608a111029fb970001adb3e6"></contenido_revista>
                </seccion_revista>
            </indice_revista> 
        </revista>

    </revistas>
<!--Los periódicos se clasifican en nacionales e internacionales.-->

    <periodicos>
        <periodico id="P0001" tipo_clase="Nacional" num_pag="45" fecha_publicacion="16/05/2021">
            <titulo>"El País"</titulo>
            <indice>
                <seccion num="1" num_pag="13" tipo_seccion="económica">
                    <articulo num="1" num_pag="2">
                        <autor>Lluís Pellicer</autor>
                        <contenido enlace_info="https://madrid.ebiblio.es/resources/60a0a4d6b3bcf20001019b17"></contenido>
                    </articulo>
                    <articulo num="2" num_pag="1">
                        <autor>Francisco Peregil</autor>
                        <contenido enlace_info="https://madrid.ebiblio.es/resources/60a0a4d6b3bcf20001019b17"></contenido>
                    </articulo>
                </seccion>
                <seccion num="2" num_pag="10" tipo_seccion="opinión">
                    <articulo num="1" num_pag="2">
                        <autor>Mario Vargas Llosa</autor>
                        <contenido enlace_info="https://madrid.ebiblio.es/resources/60a0a4d6b3bcf20001019b17"></contenido>
                    </articulo>
                    <articulo num="2" num_pag="1">
                        <autor>Elvira Lindo</autor>
                        <contenido enlace_info="https://madrid.ebiblio.es/resources/60a0a4d6b3bcf20001019b17"></contenido>
                    </articulo>
                </seccion>
                <seccion num="3" num_pag="8" tipo_seccion="deportes">
                    <articulo num="1" num_pag="2">
                        <autor>Luis Villaescusa</autor>
                        <contenido enlace_info="https://madrid.ebiblio.es/resources/60a0a4d6b3bcf20001019b17"></contenido>
                    </articulo>
                    <articulo num="2" num_pag="1">
                        <autor>Diego Torres</autor>
                        <contenido enlace_info="https://madrid.ebiblio.es/resources/60a0a4d6b3bcf20001019b17"></contenido>
                    </articulo>
                </seccion>
                <seccion num="4" num_pag="8" tipo_seccion="nacional">
                    <articulo num="1" num_pag="2">
