=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/Archivos_Individuales_Grupo/Archivos_Angel/Biblioteca.dtd
<!ELEMENT biblioteca (libro+,periodico+,revista+)>
    <!ATTLIST biblioteca nombre CDATA #REQUIRED>
	
    <!ELEMENT libro (nombre_libro,autor,paginas_libro,indice,sinopsis)>
    		<!ATTLIST libro id CDATA #REQUIRED>
			<!ATTLIST libro tipo_clase CDATA #REQUIRED>
    		<!ELEMENT nombre_libro (#PCDATA)>
    		<!ELEMENT autor (#PCDATA)>
    		<!ELEMENT paginas_libro (#PCDATA)>
    		<!ATTLIST paginas_libro numero CDATA #REQUIRED>
			<!ELEMENT indice (capitulo+)>
				<!ELEMENT capitulo (titulo,contenido_capitulo,paginas_capitulo)>
				<!ATTLIST capitulo numero CDATA #REQUIRED>

    			<!ELEMENT titulo (#PCDATA)>
    			<!ELEMENT contenido_capitulo (#PCDATA)>
    			<!ATTLIST contenido_capitulo enlace  CDATA #REQUIRED>
    			<!ELEMENT paginas_capitulo (#PCDATA)>
    			<!ATTLIST paginas_capitulo numero CDATA #REQUIRED>
			<!ELEMENT sinopsis (#PCDATA)>


            <!ELEMENT periodico (nombre_periodico,indice_periodico)>
    		<!ATTLIST periodico id CDATA #REQUIRED>
			<!ATTLIST periodico tipo_clase CDATA #REQUIRED>
    		<!ELEMENT nombre_periodico (#PCDATA)>
    		<!ATTLIST nombre_periodico aÃ±opublicacion CDATA #REQUIRED>
    		<!ELEMENT indice_periodico (seccion_periodico+)>
    			<!ELEMENT seccion_periodico (articulo+)>
    			<!ATTLIST seccion_periodico tipo_seccion CDATA #REQUIRED>

    				<!ELEMENT articulo (nombre_articulo,contenido)>
    				<!ATTLIST articulo nombre_autor CDATA #REQUIRED>
    				<!ELEMENT nombre_articulo (#PCDATA)>
    				<!ELEMENT contenido (#PCDATA)>
    				<!ATTLIST contenido informacion CDATA #REQUIRED>

                    

                    <!ELEMENT revista (titulo_revista,numerorevista,indice_revista)>
                    <!ATTLIST revista id CDATA #REQUIRED>
                    <!ATTLIST revista tipo_clase CDATA #REQUIRED>
                        <!ELEMENT titulo_revista (#PCDATA)>
                        <!ELEMENT numerorevista (#PCDATA)>
                        <!ATTLIST numerorevista numeropaginas CDATA #REQUIRED>
                        <!ELEMENT indice_revista (seccion_revista+)>
                            <!ELEMENT seccion_revista (contenido_revista)>
                            
                            <!ATTLIST seccion_revista titulo CDATA #REQUIRED>
                            <!ATTLIST seccion_revista numeropaginas CDATA #REQUIRED>
                            
                                <!ELEMENT contenido_revista (#PCDATA)>
                                <!ATTLIST contenido_revista informacion CDATA #REQUIRED>

=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/Archivos_Individuales_Grupo/Archivos_Angel/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "Biblioteca.dtd">

<biblioteca nombre="Biblioteca Publica Machado">


    <libro id="L0001" tipo_clase="Novela">

        <nombre_libro>La Reina Roja</nombre_libro>
        <autor>Juan Gomez-Jurado</autor>
        <paginas_libro numero="422"/>
        <indice>
            
                <capitulo numero="1">
                    <titulo>Un encargo</titulo>
                    <contenido_capitulo enlace="www.megustaleer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="30"/>
                </capitulo>
                <capitulo numero="2">
                    <titulo>Un Flashback</titulo>
                    <contenido_capitulo enlace="www.megustaleer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="35"/>
                </capitulo>
                
                <capitulo numero="3">
                    <titulo>Un baile</titulo>
                    <contenido_capitulo enlace="www.megustaleer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="25"/>
                </capitulo>

                <capitulo numero="4">
                    <titulo>Una Videollamada</titulo>
                   <contenido_capitulo enlace="www.megustaleer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                    inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="30"/>
                </capitulo>
        </indice> 
        <sinopsis>
            Antonia Scott es una mujer muy especial. Tiene un don que es al mismo tiempo una maldición: una extraordinaria inteligencia. Gracias a ella ha salvado decenas de vidas, pero también lo ha perdido todo. Hoy se parapeta contra el mundo en su piso casi vacío de Lavapiés, del que no piensa volver a salir.
        </sinopsis>


    </libro>
    <libro id="L0002" tipo_clase="Infantil">

        <nombre_libro>El Principito</nombre_libro>
        <autor>Antoine de Saint-Exupéry</autor>
        <paginas_libro numero="104"/>
        <indice>
           
                <capitulo numero="1">
                    <titulo>I</titulo>
                    <contenido_capitulo enlace="www.megustaleer.com">  His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="2"/>
                </capitulo>
                <capitulo numero="2">
                    <titulo>II</titulo>
                    <contenido_capitulo enlace="www.megustaleer.com">  His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="3"/>
                </capitulo>
                <capitulo numero="3">
                    <titulo>III</titulo>
                   <contenido_capitulo enlace="www.megustaleer.com">  His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                    inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="3"/>
                </capitulo>
                <capitulo numero="4">
                    <titulo>IV</titulo>
                   <contenido_capitulo enlace="www.megustaleer.com">  His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                    inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="2"/>
                </capitulo>

           
            
        </indice>
        <sinopsis>
            El principito es un cuento poético que viene acompañado de ilustraciones hechas con acuarelas por el mismo Saint-Exupéry. En él, un piloto se encuentra perdido en el desierto del Sahara después de que su avión sufriera una avería, pero para su sorpresa, es allí donde conoce a un pequeño príncipe proveniente de otro planeta. La historia tiene una temática filosófica, donde se incluyen críticas sociales dirigidas a la «extrañeza» con la que los adultos ven las cosas.
        </sinopsis>


    </libro>

    <libro  id="L0003" tipo_clase="Didáctico">

        <nombre_libro>Lenguaje de Marcas y Sistemas de gestion de la Informacion</nombre_libro>
        <autor>Raul Salgado</autor>
       <paginas_libro numero="200"/>
        <indice>
            
                <capitulo numero="1">
                    <titulo>SGML</titulo>
                    <contenido_capitulo enlace="www.edix.com">His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="18"/>
                </capitulo>
                <capitulo numero="2">
                    <titulo>Lenguaje de marcas en entornos web</titulo>
                    <contenido_capitulo enlace="www.edix.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="60"/>
                </capitulo>
                <capitulo numero="3">
                    <titulo>Gramaticas</titulo>
                    <contenido_capitulo enlace="www.edix.com">His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="8"/>
                </capitulo>
                <capitulo numero="4">
                    <titulo>Herramientas de edición de código</titulo>
                    <contenido_capitulo enlace="www.edix.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_capitulo>
                    <paginas_capitulo numero="13"/>
                </capitulo>

          
            
        </indice>
        <sinopsis>
            El objetivo principal de este libro es servir de guía y proporcionar material de apoyo a los contenidos del módulo "Lenguajes de Marcas y Sistemas de Gestión de Información" (LMSGI) de los Ciclos Formativos de Grado Superior de Informática (ASIR, DAM y DAW).

        </sinopsis>


    </libro>

    
    <revista  id="R0001" tipo_clase="informatica">
    	
    		<titulo_revista>PC computer</titulo_revista>	
    		<numerorevista numeropaginas="60"></numerorevista>
    		
    		<indice_revista>
    			<seccion_revista titulo="JavaScript" numeropaginas="20">
    				
    				<contenido_revista informacion="www.PCcomputer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_revista>

    				
    			</seccion_revista>
    			<seccion_revista titulo="Chollos pc's" numeropaginas="20">
    				
    				<contenido_revista informacion="www.PCcomputer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_revista>

    				
    			</seccion_revista>
    			<seccion_revista titulo="Mundo internet" numeropaginas="20">
    				
    				<contenido_revista informacion="www.PCcomputer.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_revista>

    				
    			</seccion_revista>
    			
    		</indice_revista>

    	</revista>

    	<revista  id="R0002" tipo_clase="corazón">

    		<titulo_revista>Que me dices</titulo_revista>	

    		<numerorevista numeropaginas="100"></numerorevista>
    		
    		<indice_revista>
    			<seccion_revista titulo="¡¡Belen Esteban se va!!" numeropaginas="20">
    				
    				<contenido_revista informacion="www.quemedices.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_revista>

    				
    			</seccion_revista>
    			<seccion_revista titulo="Seguimos the dancer" numeropaginas="30">
    				
    				<contenido_revista informacion="www.quemedices.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_revista>

    				
    			</seccion_revista>
    			<seccion_revista titulo="Chavelita nos enseña su nueva casa" numeropaginas="50">
    				
    				<contenido_revista informacion="www.quemedices.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
                        inde ad exercitum proficiscitur.</contenido_revista>

    				
    			</seccion_revista>
    			
    		</indice_revista>

    	
    	</revista>

    	<revista id="R0003" tipo_clase="coches">
    		<titulo_revista>A todo gas</titulo_revista>	
    		<numerorevista numeropaginas="80"></numerorevista>
    		
    		<indice_revista>
    			<seccion_revista titulo="Locos por el motor" numeropaginas="40">
    				
    				<contenido_revista informacion="www.atodogas.com"> His confectis rebus ac conventibus peractis, Caesar in Citeriorem Galliam revertitur atque
