=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/Archivos_Individuales_Grupo/Archivos_JMTE/BibliotecaconXSD/XSDBiblioteca.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="biblioteca">
    <xs:complexType>
      <xs:sequence>
        <!--Lo hacemos en secuencia pero podria ser con un all desordenado, ya que no tienen que ir en orden (libros,periodicos,revistas)-->
        <xs:element name="libros">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="libro">
                <!--Aqui le decimos que puede haber unbounded libros-->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre_libro" type="xs:string" />
                    <xs:element name="autor" type="xs:string" />
                    <xs:element name="paginas_libro">
                      <xs:complexType>
                        <xs:attribute name="numero" type="xs:integer" use="required" />
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="indice">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="capitulo">
                            <!--Aqui le decimos que puede haber unbounded capitulos-->
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="titulo" type="xs:string" />
                                <xs:element name="contenido_capitulo">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="enlace" type="xs:string" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="paginas_capitulo">
                                  <xs:complexType>
                                    <xs:attribute name="numero" type="xs:integer" use="required" /> <!--Atributo numero de paginas del capitulo-->
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="numero" type="xs:integer" use="required" /> <!--Atributo numero de capitulos del libro-->
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="sinopsis" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required" /> <!--Atributo id tipo de articulo de la biblioteca, se hace tipo ID para que sea unico-->
                  <xs:attribute name="tipo_clase" type="xs:string" use="required" /> <!--Atributo tipo de libro-->
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>

        </xs:element>
        <xs:element name="periodicos">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="periodico">
                <!--Aqui le decimos que puede haber unbounded periodicos-->
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre_periodico">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="añopublicacion" type="xs:integer" use="required" /> <!--Como solo piden el año, hacemos tipo integer-->
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="indice_periodico">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="seccion_periodico">
                            <!--Aqui le decimos que puede haber unbounded secciones-->
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="articulo">
                                  <!--Aqui le decimos que puede haber unbounded articulos-->
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="nombre_articulo" type="xs:string" />
                                      <xs:element name="contenido">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute name="informacion" type="xs:string" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nombre_autor" type="xs:string" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="tipo_seccion" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                  <xs:attribute name="tipo_clase" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>

        </xs:element>

        <xs:element name="revistas">
          <xs:complexType>
            <xs:sequence>

              <xs:element maxOccurs="unbounded" name="revista">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="titulo_revista" type="xs:string" />
                    <xs:element name="numerorevista">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:unsignedByte">
                            <xs:attribute name="numeropaginas" type="xs:integer" use="required" />
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="indice_revista">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="seccion_revista">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="contenido_revista">
                                  <xs:complexType>
                                    <xs:simpleContent>
                                      <xs:extension base="xs:string">
                                        <xs:attribute name="informacion" type="xs:string" use="required" />
                                      </xs:extension>
                                    </xs:simpleContent>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="titulo" type="xs:string" use="required" />
                              <xs:attribute name="numeropaginas" type="xs:integer" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="id" type="xs:ID" use="required" />
                  <xs:attribute name="tipo_clase" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>

          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required" />
    </xs:complexType>


  </xs:element>
</xs:schema>

=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/Archivos_Individuales_Grupo/Archivos_JMTE/BibliotecaconXSD/BibliotecaXSD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<!--ESta primera linea tiene que ir sin ningun espacio ni nada anteriormente escrito, ni tan siquiera un comentario-->

<!--Vamos a elaborar una estructura de base de datos en XML que permita almacenar los datos de una biblioteca en la red. Para ello se pide que elabores un DTD que permita validar los documentos XML con las siguientes características:
Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos. Todos los documentos están identificados por el atributo Id.
Para los libros este atributo empieza con la letra “L” seguido de 4 dígitos identificativos.
Para los periódicos este atributo empieza por la letra “P” seguido de los 4 dígitos identificativos.
En el caso de las revistas empieza por la letra “R”.
-->

<!--standalone=no nos indica que el documento depende
de un documento de validacion externo-->





<biblioteca nombre="Biblioteca Pública Madrid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation= "XSDBiblioteca.xsd"> <!--Aqui le empotramos el xsd para validar-->
	
    
 
<!--Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo identificativo de su clase denominado tipo_clase. Dentro de cada libro se tiene un título, varios capítulos con el título en su interior, un índice y una sinopsis. Tanto en libro como en capítulo existe un atributo que contiene el número de páginas del libro o del capítulo, según corresponda. Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a la información.-->

   
        <libro id="L0001" tipo_clase="Novela">

            <nombre_libro>La Mente Criminal</nombre_libro>
            <autor>Vicente Garrido</autor>
            <paginas_libro numero="320"/>
            <indice>
                
                    <capitulo numero="1">
                        <titulo>El mundo del asesino en serie</titulo>
                        <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>
                    <capitulo numero="2">
                        <titulo>Jack el Destripador y el nacimiento de la ciencia forense</titulo>
                        <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>
                    
                    <capitulo numero="3">
                        <titulo>La huella del crimen</titulo>
                        <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>

                    <capitulo numero="1">
                        <titulo>El monstruo de la Machala</titulo>
                       <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>

                
                
            </indice>
            <sinopsis>
                ¿Cómo actúan los asesinos en serie? ¿Para qué sirve el análisis del perfil genético (ADN)? ¿Qué es el modus operandi y la firma de un asesino? ¿Cuáles son los métodos de investigación de la Policía? 
				Los interesados en las ciencias sociales y criminológicas y los estudiantes y profesionales de las diferentes policías encontrarán en La mente criminal nociones esenciales de criminología forense aplicadas a casos criminales que conmovieron a una sociedad entera e incluso al mundo. Al analizar la forma de actuar y de pensar de los asesinos seriales su autor, Vicente Garrido, proporciona al lector unos conocimientos sobre cómo éstos crean su propia realidad y las formas peculiares en que llevan a la práctica sus terribles fantasías. De Jack el Destripador a Tony King, pasando por criminales notables de España (Gilberto Chamba, "el Monstruo de Machala", el Asesino de la Baraja) y del mundo (Richard Ramírez, Ted Bundy), este libro describe de modo riguroso pero fácilmente comprensible el mundo de los asesinos en serie, al tiempo que introduce apasionantes historias de revelación de las ciencias forenses.
            </sinopsis>


        </libro>


         <libro id="L0001" tipo_clase="Infantil">

            <nombre_libro>Sapo y sepo, inseparables</nombre_libro>
            <autor>Arnold Lobel</autor>
            <paginas_libro numero="220"/>
            <indice>
               
                    <capitulo numero="1">
                        <titulo>Mañana</titulo>
                        <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
                    <capitulo numero="2">
                        <titulo>La Cometa</titulo>
                        <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
                    <capitulo numero="3">
                        <titulo>Escalofrios</titulo>
                       <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
                    <capitulo numero="1">
                        <titulo>El sombrero</titulo>
                       <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
