=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/Archivos_Individuales_Grupo/Archivos_JMTE/BibliotecaconDTD/DTDBiblioteca.dtd
<!ELEMENT biblioteca (libros,periodicos,revistas)>
    <!ATTLIST biblioteca nombre CDATA #REQUIRED>

	<!--Vamos a elaborar una estructura de base de datos en XML que permita almacenar los datos de una biblioteca en la red. Para ello se pide que elabores un DTD que permita validar los documentos XML con las siguientes características:
Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos. Todos los documentos están identificados por el atributo Id.
Para los libros este atributo empieza con la letra “L” seguido de 4 dígitos identificativos.
Para los periódicos este atributo empieza por la letra “P” seguido de los 4 dígitos identificativos.
En el caso de las revistas empieza por la letra “R”.

Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo identificativo de su clase denominado tipo_clase. Dentro de cada libro se tiene un título, varios capítulos con el título en su interior, un índice y una sinopsis. Tanto en libro como en capítulo existe un atributo que contiene el número de páginas del libro o del capítulo, según corresponda. Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a la información.-->    	
    	
    	
    	
    		
			<!ELEMENT libros (libro+)>
    		<!ELEMENT libro (nombre_libro,autor,paginas_libro,indice,sinopsis)>
			<!-- En id se pone que es de tipo ID para que se identifique como valor unico y no se pueda repetir-->
    		<!ATTLIST libro id ID #REQUIRED>
			<!ATTLIST libro tipo_clase CDATA #REQUIRED>
    		<!ELEMENT nombre_libro (#PCDATA)>
    		<!ELEMENT autor (#PCDATA)>
    		<!ELEMENT paginas_libro (#PCDATA)>
    		<!ATTLIST paginas_libro numero CDATA #REQUIRED>
			<!ELEMENT indice (capitulo+)>
				<!ELEMENT capitulo (titulo,contenido_capitulo,paginas_capitulo)>
				<!ATTLIST capitulo numero CDATA #REQUIRED>

    			<!ELEMENT titulo (#PCDATA)>
    			<!ELEMENT contenido_capitulo (#PCDATA)>
    			<!ATTLIST contenido_capitulo enlace  CDATA #REQUIRED>
    			<!ELEMENT paginas_capitulo (#PCDATA)>
    			<!ATTLIST paginas_capitulo numero CDATA #REQUIRED>
			<!ELEMENT sinopsis (#PCDATA)>
    			
<!--Los periódicos se clasifican en nacionales e internacionales. Cada periódico contiene el atributo tipo_clase identificativo de la clase a la que pertenece y un atributo que incluye la fecha de publicación.
-->
<!--Dentro de los periódicos tenemos secciones y un índice. Cada sección debe contener un atributo identificativo del tipo de sección, que puede ser: económica, opinión, deportes, nacional o internacional. Las secciones se dividen en artículos, en donde se define en un atributo el autor. Finalmente, el contenido será el último elemento del árbol, que necesita un atributo que referencie a la información.-->


    	
    	
			<!ELEMENT periodicos (periodico+)>
    		<!ELEMENT periodico (nombre_periodico,indice_periodico)>
    		<!ATTLIST periodico id ID #REQUIRED>
			<!ATTLIST periodico tipo_clase CDATA #REQUIRED>
    		<!ELEMENT nombre_periodico (#PCDATA)>
    		<!ATTLIST nombre_periodico añopublicacion CDATA #REQUIRED>
    		<!ELEMENT indice_periodico (seccion_periodico+)>
    			<!ELEMENT seccion_periodico (articulo+)>
    			<!ATTLIST seccion_periodico tipo_seccion CDATA #REQUIRED>

    				<!ELEMENT articulo (nombre_articulo,contenido)>
    				<!ATTLIST articulo nombre_autor CDATA #REQUIRED>
    				<!ELEMENT nombre_articulo (#PCDATA)>
    				<!ELEMENT contenido (#PCDATA)>
    				<!ATTLIST contenido informacion CDATA #REQUIRED>

<!--Las revistas a su vez son clasificadas en: informática, corazón, coches, investigación y otras. Cada revista tiene el atributo tipo_clase identificativo de la clase a la que pertenece. -->
<!--Dentro de cada revista tenemos el título, el número de la revista, un índice de contenido y las secciones. En cada sección y en la revista se tiene un atributo que contiene el número de páginas. Además, en cada sección se tiene la parte denominada contenido, en la que se tiene un atributo con un enlace a la información. De igual forma que en los anteriores, la última etiqueta del árbol debe ser el contenido con un atributo que referencia al contenido.-->

    	
    	
			<!ELEMENT revistas (revista+)>
    		<!ELEMENT revista (titulo_revista,numerorevista,indice_revista)>
			<!ATTLIST revista id ID #REQUIRED>
    		<!ATTLIST revista tipo_clase CDATA #REQUIRED>
    			<!ELEMENT titulo_revista (#PCDATA)>
    			<!ELEMENT numerorevista (#PCDATA)>
    			<!ATTLIST numerorevista numeropaginas CDATA #REQUIRED>
    			<!ELEMENT indice_revista (seccion_revista+)>
    				<!ELEMENT seccion_revista (contenido_revista)>
					
    				<!ATTLIST seccion_revista titulo CDATA #REQUIRED>
    				<!ATTLIST seccion_revista numeropaginas CDATA #REQUIRED>
    				
    					<!ELEMENT contenido_revista (#PCDATA)>
    					<!ATTLIST contenido_revista informacion CDATA #REQUIRED>

=== ITTDAW/Actividad2LdM/ACTIVIDAD_2_XML_DTD_XSD/Archivos_Individuales_Grupo/Archivos_JMTE/BibliotecaconDTD/BibliotecaDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?> 

<!--ESta primera linea tiene que ir sin ningun espacio ni nada anteriormente escrito, ni tan siquiera un comentario-->
<!--standalone=no nos indica que el documento depende
de un documento de validacion externo-->


<!--Vamos a elaborar una estructura de base de datos en XML que permita almacenar los datos de una biblioteca en la red. Para ello se pide que elabores un DTD que permita validar los documentos XML con las siguientes características:
Existen tres tipos de documentos almacenados en la biblioteca: libros, revistas y periódicos. Todos los documentos están identificados por el atributo Id.
Para los libros este atributo empieza con la letra “L” seguido de 4 dígitos identificativos.
Para los periódicos este atributo empieza por la letra “P” seguido de los 4 dígitos identificativos.
En el caso de las revistas empieza por la letra “R”.
-->




<!DOCTYPE biblioteca SYSTEM "DTDBiblioteca.dtd">


<biblioteca nombre="Biblioteca Pública Madrid">
	
    
<libros>
<!--Los libros a su vez son clasificados en novela, infantil o didáctico. Cada libro contiene un atributo identificativo de su clase denominado tipo_clase. Dentro de cada libro se tiene un título, varios capítulos con el título en su interior, un índice y una sinopsis. Tanto en libro como en capítulo existe un atributo que contiene el número de páginas del libro o del capítulo, según corresponda. Cada capítulo contiene un elemento denominado contenido, en el que se tiene un atributo con el enlace a la información.-->

   
        <libro id="L0001" tipo_clase="Novela">

            <nombre_libro>La Mente Criminal</nombre_libro>
            <autor>Vicente Garrido</autor>
            <paginas_libro numero="320"/>
            <indice>
                
                    <capitulo numero="1">
                        <titulo>El mundo del asesino en serie</titulo>
                        <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>
                    <capitulo numero="2">
                        <titulo>Jack el Destripador y el nacimiento de la ciencia forense</titulo>
                        <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>
                    
                    <capitulo numero="3">
                        <titulo>La huella del crimen</titulo>
                        <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>

                    <capitulo numero="1">
                        <titulo>El monstruo de la Machala</titulo>
                       <contenido_capitulo enlace="www.contenido1.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="20"/>
                    </capitulo>

                
                
            </indice>
            <sinopsis>
                ¿Cómo actúan los asesinos en serie? ¿Para qué sirve el análisis del perfil genético (ADN)? ¿Qué es el modus operandi y la firma de un asesino? ¿Cuáles son los métodos de investigación de la Policía? 
				Los interesados en las ciencias sociales y criminológicas y los estudiantes y profesionales de las diferentes policías encontrarán en La mente criminal nociones esenciales de criminología forense aplicadas a casos criminales que conmovieron a una sociedad entera e incluso al mundo. Al analizar la forma de actuar y de pensar de los asesinos seriales su autor, Vicente Garrido, proporciona al lector unos conocimientos sobre cómo éstos crean su propia realidad y las formas peculiares en que llevan a la práctica sus terribles fantasías. De Jack el Destripador a Tony King, pasando por criminales notables de España (Gilberto Chamba, "el Monstruo de Machala", el Asesino de la Baraja) y del mundo (Richard Ramírez, Ted Bundy), este libro describe de modo riguroso pero fácilmente comprensible el mundo de los asesinos en serie, al tiempo que introduce apasionantes historias de revelación de las ciencias forenses.
            </sinopsis>


        </libro>


         <libro id="L0002" tipo_clase="Infantil">

            <nombre_libro>Sapo y sepo, inseparables</nombre_libro>
            <autor>Arnold Lobel</autor>
            <paginas_libro numero="220"/>
            <indice>
               
                    <capitulo numero="1">
                        <titulo>Mañana</titulo>
                        <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
                    <capitulo numero="2">
                        <titulo>La Cometa</titulo>
                        <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
                    <capitulo numero="3">
                        <titulo>Escalofrios</titulo>
                       <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>
                    <capitulo numero="1">
                        <titulo>El sombrero</titulo>
                       <contenido_capitulo enlace="www.contenido2.com"> Auctor commodo vivamus molestie suscipit tincidunt proin cum facilisi enim euismod tempor, facilisis erat blandit aptent sapien libero nec hac semper. Dictum tempus dis ultrices conubia feugiat nunc himenaeos dictumst quis, justo potenti mi lectus parturient porta fusce ad luctus, facilisi elementum vel magnis fames aptent inceptos leo. Dignissim suscipit felis nec tristique rhoncus magnis facilisis volutpat proin, nisi quis leo eu cursus accumsan enim lobortis pretium erat, nisl montes neque curabitur lacinia justo inceptos urna.</contenido_capitulo>
                        <paginas_capitulo numero="30"/>
                    </capitulo>

               
                
            </indice>
            <sinopsis>
